Enable the load command and use that for loading the uEnv and bootscript
ayufan-pine64/u-boot-pine64 pull request #2
Opened 2017-07-25 11:49 UTC by shadeslayer

2017-07-25 12:42 UTC, ayufan requested changes

2017-07-25 12:42 UTC, ayufan commented on include/configs/sun50iw1p1.h
> +		"for prefix in / /boot/; do if test -e mmc ${boot_part} ${bootenv_filename}; then load mmc ${boot_part} ${load_addr} ${prefix}${bootenv_filename}; fi; done\0" \
Should we start from longest prefix first? `/boot`, `/`.

2017-07-25 12:44 UTC, shadeslayer commented on include/configs/sun50iw1p1.h
> +		"for prefix in / /boot/; do if test -e mmc ${boot_part} ${bootenv_filename}; then load mmc ${boot_part} ${load_addr} ${prefix}${bootenv_filename}; fi; done\0" \
I think having a hierarchy of / and then /boot makes more sense, but I don't really have a strong opinion on this.

2017-07-25 12:45 UTC, ayufan commented on include/configs/sun50iw1p1.h
> +		"for prefix in / /boot/; do if test -e mmc ${boot_part} ${bootenv_filename}; then load mmc ${boot_part} ${load_addr} ${prefix}${bootenv_filename}; fi; done\0" \
Can you check what is the order in mainline u-boot? we should have the same then.

2017-07-25 12:53 UTC, shadeslayer commented on include/configs/sun50iw1p1.h
> +		"for prefix in / /boot/; do if test -e mmc ${boot_part} ${bootenv_filename}; then load mmc ${boot_part} ${load_addr} ${prefix}${bootenv_filename}; fi; done\0" \
It seems to be /uEnv.txt and /boot/uEnv.txt in include/configs/bav335x.h

2017-07-27 18:30 UTC, ayufan approved these changes

2017-07-27 18:50 UTC, merged